name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        IMAGE_TAG=${{ github.sha }}
        docker build -t yourdockerhubusername/flask-app:$IMAGE_TAG ./flask-app
        docker push yourdockerhubusername/flask-app:$IMAGE_TAG

    - name: Update Kubernetes deployment image tag
      run: |
        IMAGE_TAG=${{ github.sha }}
        sed -i "s|image: yourdockerhubusername/flask-app:.*|image: yourdockerhubusername/flask-app:$IMAGE_TAG|g" ./kube/app/deployment.yaml

    - name: Commit and push updated manifest
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add ./kube/app/deployment.yaml
        git commit -m "Update image tag to $IMAGE_TAG"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
